bitcoin-sv/spv-wallet

actions/destinations/routes.go, actions/destinations/update.go, actions/transactions/routes.go, actions/transactions/update.go, actions/xpubs/routes.go, actions/xpubs/routes_test.go, actions/xpubs/update.go, config/envs/development.json, graph/generated/generated.go, graph/schema.graphqls, graph/schema.resolvers.go
=> Added update xPub metadata route

graph/generated/generated.go, graph/schema.graphqls, graph/schema.resolvers.go
=> Changed tx_id to id int query transaction and mutation transaction_metadata

actions/paymail/create.go
=> Fixed paymail action according to new bux method signature

gqlgen.yml, graph/admin.graphqls, graph/admin.resolvers.go, graph/generated/generated.go, graph/schema.graphqls
=> Added missing admin graphql endpoints for paymail

graph/schema.resolvers.go
=> Fixed init of model options in graphql resolver

config/config.go, config/services.go
=> Added notifications config

actions/access_keys/count.go, actions/access_keys/routes.go, actions/destinations/count.go, actions/destinations/routes.go, actions/transactions/count.go, actions/transactions/routes.go
=> Added missing count actions in http endpoints

config/envs/docker-compose.json, docker-compose.yml
=> Add depends_on to docker-compose and disable monitoring

actions/admin/record.go, actions/admin/routes.go, graph/admin.graphqls, graph/admin.resolvers.go, graph/generated/generated.go
=> Added AdminRecordTransaction

config/config.go, config/envs/development.json, config/services.go
=> Added cluster config options for bux

actions/admin/record.go, graph/admin.resolvers.go
Bux doesn't care who inserts a transaction and no need to trow an error here.
=> Return transaction from DB when recording a transaction that is already inserted

actions/admin/paymail_addresses.go, actions/admin/routes.go
=> Added http endpoints for creating and deleting paymails as admin

config/services.go
=> Fixed redis url parsing for cluster coordinator

config/config.go, config/envs/development.json, config/envs/docker-compose.json, config/envs/production.json, config/envs/staging.json, config/envs/test.json, config/services.go
Usage of mapi fee quotes.
Continue of https://github.com/BuxOrg/bux/pull/325
=> feat: usage of mapi fee quotes

start-bux-server.sh
=> feat(BUX-249): support for docker-compose in starting script

go.mod, go.sum
=> chore(BUX-XXX): update bux to v0.7.0

start-bux-server.sh
=> feat(BUX-361): env update in script that runs bux-server

README.md, config.example.yaml, config/defaults.go
Changed xpub key value to ensure compatibility with keys in other repositories
=> fix(BUX-000): replace default xpub to match defaults in other repos

cmd/server/main.go, config/config_test.go, config/validate.go
=> chore(BUX-456): config validation first

actions/base/routes.go, actions/base/routes_test.go
=> fix(BUX-460): change pprof methods to get in replace of patch

.github/workflows/release.yml, release/Dockerfile, release/entrypoint.sh
=> fix(BUX-449): docker image cannot be run

cmd/server/main.go, config.example.yaml, config/config.go, config/config_test.go, config/defaults.go, config/services.go, config/validate_paymail.go, config/validate_paymail_test.go, server/server.go
=> feat(BUX-515): removed PaymailConfig.Enabled

config/defaults.go, config/services.go, go.mod, go.sum
=> chore: bump bux ver 0.14.1 -> 0.14.2

.github/workflows/run-tests.yml, config.example.yaml, config/config.go, config/defaults.go, config/nodes.go, go.mod, go.sum
=> feat(BUX-500): add DeploymentID to bux-server configuration

logging/logging.go
=> feat(BUX-000): logger fix for kibana

config.example.yaml, config/config.go, config/defaults.go, config/services.go, go.mod, go.sum, metrics/collector.go, metrics/global.go, metrics/metrics.go, metrics/naming.go, server/server.go
This PR is tightly coupled with the one from `bux` repository - they should be tested together. 
Generally, I introduced metrics collection in `bux` package and initialized it within `bux-server`. 
> NOTE: Additional metrics of incoming requests will be implemented when transition to `gin` is complete. 
The metrics that prometheus can collect are available at the `/metrics` endpoint - which is a standard approach. 
If you'd like to test it locally with local Prometheus & Grafana - contact me for help with configuration and example dashboards. 
It can also be tested manually by checking the content od `/metrics` endpoint. 
Example dashboard:
=> feat(BUX-566): metrics

config.example.yaml, server/auth/middleware.go
Changed postgres to postgresql, mark mongodb as experimental
=> BUX-623/ Postgresql engine
